# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 80bfdc67a8a1753053078a1c724226aa536c5ea425cae44b388b65b0bfec8e1fbcdf825f84674e73112bfde198d0860da38618529e097af35805678b91dcb051
  slack_token: <%= ENV["SLACK_TOKEN"] %>
  zendesk:
    url: https://getchef.zendesk.com/api/v2
    username: <%= ENV["ZENDESK_USER"] %>
    token: <%= ENV["ZENDESK_TOKEN"] %>

test:
  secret_key_base: c042b301c7c688a62f44dfdc2655dd07e0e4870f2164c08ba463f03c4e7dd8469fb4f758c136b4ae75dfa34ab201595c35d8a33505cf767396e5b6ab88779262
  slack_token: a1B2c3D4e5F6
  zendesk:
    url: https://getchef.zendesk.com/api/v2
    username: <%= ENV["ZENDESK_USER"] %>
    token: <%= ENV["ZENDESK_TOKEN"] %>


# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  slack_token: <%= ENV["SLACK_TOKEN"] %>
  zendesk:
    url: https://getchef.zendesk.com/api/v2
    username: <%= ENV["ZENDESK_USER"] %>
    token: <%= ENV["ZENDESK_TOKEN"] %>


